version: '3.8' 
services:
  postgres:
    image: postgres:17
    container_name: gr-db
    environment:
      POSTGRES_USER: my_user         
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database    
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "6952:5432"

volumes:
  postgres_data:

